### ISSUE TITLE
How about TypeScript support?

### ISSUE THREAD

**Issue by Le0Michine** [atanas-angelov-dev/vue-router-multiguard#1]
Is it planned to support type script users?

**Comment by atanas-dev** [comment]
It seems I've completely missed this ticket - sorry about that!

I just pushed 1.0.3 which adds TypeScript support so I'll be closing this issue.
Note that I've barely used TypeScript so please let me know if I've made any mistakes or could improve the implementation.

**Comment by lifenautjoe** [comment]
How does one declare a multiguard with TypeScript? Perhaps something for the docs?

**Comment by atanas-dev** [comment]
@lifenautjoe to be honest I haven't used TypeScript in a very long time (not due to the lack of interest though) however there's a module definition file available:
https://github.com/atanas-angelov-dev/vue-router-multiguard/blob/master/types/index.d.ts

Hopefully that helps you out.
