### ISSUE TITLE
es module export?

### ISSUE THREAD

**Issue by loeffel-io** [atanas-angelov-dev/vue-router-multiguard#11]
Hey, are there any plans to support es modules? vite crashs in case of the non existing es target 

Thanks!

**Comment by atanas-dev** [comment]
There are no plans, no. If it's causing you too much trouble you can always copy-paste the contents of index.js - it's an extremely simple module (that can be simplified some more too) :)

**Comment by loeffel-io** [comment]
alright, thanks for the answer!
