### ISSUE TITLE
Issue with next() not ending a function

### ISSUE THREAD

**Issue by johndatserakis** [atanas-angelov-dev/vue-router-multiguard#4]
Hi there - great job on this. I believe there is a definite need for a middleware-type plugin for vue-router. I know for my uses, I need something like this.

In attempting to use it, I'm finding an issue with a pretty simple example - maybe you can take a look and let me know if I'm using it correctly.

I, like a lot of people looking to use a plugin like this, want to run what basically amounts to middleware. When one middleware is done, the next one in line runs. Based on your instruction, by using `next()` with something else other than `undefined`, then it should stop the middleware function right there in place and not proceed futher. 

I'm finding that the middleware function code is still continued after the `next(true)` or `next({name: 'before'})`. What's good is that `middlewareTwo` is never called, but the `middlewareOne` function should never print the second `console.log`. See below:

```javascript
// Middleware functions
const middlewareOne = function(to, from, next) {
    console.log('top of middlewareOne')
    
    // Either one of these produces the same result
    next(true)
    /// next({name: 'before'})

    console.log('bottom of middlewareOne')
}

const middlewareTwo = function(to, from, next) {
    console.log('top of middlewareTwo')
    next()
    console.log('bottom of middlewareTwo')
}

// Route def
{
    path: '/',
    name: 'home',
    component: Home,
    beforeEnter: multiguard([middlewareOne, middlewareTwo])
},
```

In the both versions, the console produces:

```javascript
// console
'top of middlewareOne'
'bottom of middlewareOne'
```

Shouldn't `bottom of middlewareOne` never get printed? Thank you.

**Comment by atanas-dev** [comment]
Hi @johndatserakis ,

This is expected - `next()` is just a callback - it does not terminate function execution (that's just how JavaScript works). It will, however, NOT call the next guard in line if `next()` is called with an argument other than undefined, as you've already seen.

Usually you should just call `next()` at the end of your function or async/promise chain. It doesn't really make much sense to do anything after it.

**Comment by johndatserakis** [comment]
True - got it. I was hoping to avoid having to deal with absolute if/else statements in the middleware. 

No problem, the plugin is nice for the features it already provides. Thank you.

**Comment by atanas-dev** [comment]
You can always use `return;` or `return next();` if you want it to be obvious why you are using it :)

**Comment by johndatserakis** [comment]
Thanks - `return next()` actually does exactly what I was looking for, and if I don't pass anything in `return next()`, it goes to the next middleware. Looks good, thanks.
