### ISSUE TITLE
next is not a function

### ISSUE THREAD

**Issue by nanadjei** [atanas-angelov-dev/vue-router-multiguard#6]
Tried to navigate to the page I have my middleware set but am getting next is not a function.

**Comment by atanas-dev** [comment]
Hi @qodehub-nanadjei ,

Could you please your middleware and the vue-router version you are using? Also make sure this is how you're calling multiguard:
`beforeEnter: multiguard([guard1, guard2])`
rather than
`beforeEnter: () => multiguard([guard1, guard2])`, for example.

**Comment by nanadjei** [comment]
vue-router: "^3.0.2"

**Comment by atanas-dev** [comment]
Could you please copy-paste your usage of the multiguard function (`beforeEnter: ...`)?

**Comment by nanadjei** [comment]
Asking me to paste the usage drew my attention to something I was doing wrong. I have fixed it. Thank you.
