### ISSUE TITLE
An example how to use multiguards for Global guards like Router.beforeEach

### ISSUE THREAD

**Issue by martinhalik** [atanas-angelov-dev/vue-router-multiguard#8]
Hello, I am new to Vue and I have problem setting this up to work for all routes globally, is it even possible?

**Comment by martinhalik** [comment]
This helped: https://github.com/atanas-dev/vue-router-multiguard/issues/6#issuecomment-515133237

Instead of 
```
Router.beforeEach((to, from, next) => {
  multiguard([guard1(to, from, next), guard2(to, from, next)]);
});
```

I've used this and it works
`Router.beforeEach(multiguard([guard1,guard2]));`

**Comment by emiliemarchand** [comment]
I had the same question, It would be useful to put the example in the documentation.
