### ISSUE TITLE
Multiple Guard won't stop if the first guard is met

### ISSUE THREAD

**Issue by alkeincodes** [atanas-angelov-dev/vue-router-multiguard#9]
Hello! I created this multiple guards for routes to specific userRole.
Example:
   when I used this `multiguard([authRouteGuard, nurseGuard])` the page is accessible to authenticated nurse only - which is what i want. However, when I use `multiguard([authRouteGuard, nurseGuard, doctorGuard])` I can't access the page even if I', in a right userRole for that page. Seems like the iteration of each guard didn't stop. Not sure if I implemented this correctly. Need help.
```
export const authRouteGuard = (to, from, next) => {
    if(login) next()
};

export const nurseGuard = (to, from, next) => {
        let role = store.getters['userRole'].selected_profile;
        if (role === 'nurse') {
            next();
        } else {
            next(from.path)
        }
};

export const doctorGuard = (to, from, next) => {
        let role = store.getters['userRole'];
        console.log(from)
        if (role === 'doctor') {
            next();
        } else {
            next(from.path)
        }
};

export const addRouteGuard = routes =>
    routes.map(r => {
        r.beforeEnter = multiguard([authRouteGuard, nurseGuard, doctorGuard]);
        r.props = true;
        return r;
    });
```

**Comment by atanas-dev** [comment]
Hi @alkeincodes ,

From what I understand you wish to allow users with **either** nurse **or** doctor roles to access the page - is this correct?
If that's the case, multiguards are in an **and** relationship i.e. all guards must pass for the user to access the route and in this case your nurseGuard and doctorGuard cancel each other as `role` can only be one or the other.

To have an **or** relationship you'll have to combine the guards into something like this:
```js
export const authRouteGuard = (to, from, next) => {
    if(login) next()
};

export const userRoleGuard = (roles) => (to, from, next) => {
    let role = store.getters['userRole'];

    if (roles.indexOf(role) !== -1) {
        next();
        return;
    }

    next(from.path);
}

export const addRouteGuard = routes =>
    routes.map(r => {
        r.beforeEnter = multiguard([authRouteGuard, userRoleGuard(['nurse', 'doctor'])]);
        r.props = true;
        return r;
    });
```
_Note: I have not tested the above code._

**Comment by alkeincodes** [comment]
@atanas-dev thank you for this help right now I can access the pages with this role but is there anyway restricting the `nurse` to access doctor's page in this `addRouteGuard()`?

**Comment by atanas-dev** [comment]
@alkeincodes you will need to have different guards on doctor-only pages that permit the doctor role only - you can reuse the above example and only pass the doctor role as an argument:
```js
// doctor-only:
r.beforeEnter = multiguard([authRouteGuard, userRoleGuard(['doctor'])]);
// doctor OR nurse:
r.beforeEnter = multiguard([authRouteGuard, userRoleGuard(['nurse', 'doctor'])]);
```
